config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/superadmin', as: 'rails_admin'
  resources :locations
  root to: 'locations#index'
end

app/models/location.rb
class Location < ActiveRecord::Base

  def within_range
    locations = Location.where.not(id: self.id)
    rgeo_factory = RGeo::Geographic.spherical_factory(:srid => 4326)
    locations.each do |location|
      # distance in meters
      rgeo_factory.point(self.lonlat.x, self.lonlat.y).distance(location.lonlat)

    end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  def show
    @location = Location.find(params[:id])
    @nearby = @location.within_range
  end

  def index
    @locations = Location.all
  end

  def new
    @location = Location.new
  end

  def create
    @location = Location.create(location_params)
    # Creates and returns a geographic factory that does not include a a projection,
    # and which performs calculations assuming a spherical earth. In other words, geodesics
    # are treated as great circle arcs, and geometric calculations are handled accordingly.
    # Size and distance calculations report results in meters. This implementation is thus ideal
    # for everyday calculations on the globe in which good accuracy is desired,
    # but in which it is not deemed necessary to perform the complex ellipsoidal calculations needed for greater precision.
    factory = RGeo::Geographic.spherical_factory(:srid => 4326)
    # "101.123123 3.123123"
    point = factory.point(params[:location][:lonlat].split(" ")[0] , params[:location][:lonlat].split(" ")[1])
    @location.lonlat = point
    if @location.save
      redirect_to locations_path
    end
  end

  private

  def location_params
    params.require(:location).permit(:lonlat)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Postgissample</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/locations/index.html.slim
h1 = link_to "New", new_location_path

- @locations.each do |e|
  div
    = link_to e.lonlat, location_path(e.id)

app/views/locations/new.html.slim
= form_for @location do |f|
  - if @location.errors.any?
    #error_explanation
      h3 = "#{pluralize(@location.errors.count, "error")} prohibited this location from being saved:"
      ul
        - @location.errors.full_messages.each do |message|
          li = message
  div
    = f.text_field :lonlat
  = f.submit "Create Location"

app/views/locations/show.html.slim
= @location.lonlat
h1 Nearby